from .base import *  # noqa

DEBUG = False

# In production you MUST set ALLOWED_HOSTS.
if not ALLOWED_HOSTS:
    raise RuntimeError("ALLOWED_HOSTS is required in production")

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"

SECURE_SSL_REDIRECT = True if SECURE_SSL_REDIRECT is None else SECURE_SSL_REDIRECT
SECURE_HSTS_SECONDS = int(env("SECURE_HSTS_SECONDS", default="2592000"))  # 30 days
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", default=True)
SECURE_HSTS_PRELOAD = env.bool("SECURE_HSTS_PRELOAD", default=True)
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"

# Admin hardening
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"

